// web/src/lib/components/createProject/Tabs.svelte
<script lang="ts">
import { getContext } from "svelte";
import type { Writable } from "svelte/store";

let tab: Writable<string> = getContext("Tabs");
</script>

<div class="w-[80%] h-[5px] flex gap-3 select-none">
	<div
		class="w-[33.33333%] h-full cursor-pointer transition-all duration-1000"
		on:click="{() => tab.set('provider')}">
		<div
			class="{`w-full h-full ${
				$tab === 'provider'
					? 'bg-dark-color-accent'
					: 'bg-dark-bgMuted4'
			} rounded-md`}">
		</div>
		<h5
			class="font-montserrat text-black dark:text-white font-semibold my-2">
			1. Choose a provider
		</h5>
	</div>
	<div
		class="w-[33.33333%] h-full cursor-pointer transition-all duration-1000"
		on:click="{() => tab.set('repo')}">
		<div
			class="{`w-full h-full ${
				$tab === 'repo' ? 'bg-dark-color-accent' : 'bg-dark-bgMuted4'
			} rounded-md`}">
		</div>
		<h5
			class="font-montserrat text-black dark:text-white font-semibold my-2">
			2. Pick a repository
		</h5>
	</div>
	<div
		class="w-[33.33333%] h-full cursor-pointer transition-all duration-1000"
		on:click="{() => tab.set('details')}">
		<div
			class="{`w-full h-full ${
				$tab === 'details' ? 'bg-dark-color-accent' : 'bg-dark-bgMuted4'
			} rounded-md`}">
		</div>
		<h5
			class="font-montserrat text-black dark:text-white font-semibold my-2">
			3. Project Details
		</h5>
	</div>
</div>

// web/components/Projects/Tabs.tsx
import React from "react";

const Tabs: React.FC<{ tab; setTab }> = ({ tab, setTab }) => (
  <ul className="cursor-pointer grid grid-cols-3 gap-4 mt-8 select-none h-2">
    <div
      className={`w-full transition-colors duration-300 ${
        tab === "provider" ? "bg-dark-color-accent" : "bg-gray-700"
      } rounded-xl h-2 relative`}
      onClick={() => setTab("provider")}
    >
      <span className="absolute mt-4 font-semibold font-montserrat">
        1. Choose a provider
      </span>
    </div>
    <div
      className={`w-full transition-colors duration-300 ${
        tab === "repo" ? "bg-dark-color-accent" : "bg-gray-700"
      } rounded-xl h-2 relative`}
      onClick={() => setTab("repo")}
    >
      <span className="absolute mt-4 font-semibold font-montserrat">
        2. Pick a repository
      </span>
    </div>
    <div
      className={`w-full transition-colors duration-300 ${
        tab === "details" ? "bg-dark-color-accent" : "bg-gray-700"
      } rounded-xl h-2 relative`}
      onClick={() => setTab("details")}
    >
      <span className="absolute mt-4 font-semibold font-montserrat">
        3. Project details
      </span>
    </div>
  </ul>
);
export default Tabs;
