// web/src/lib/components/createProject/Provider.svelte
<script lang="ts">
import { getContext } from "svelte";
import type { Writable } from "svelte/store";
import Buttons from "./c/Buttons.svelte";

let tab: Writable<string> = getContext("Tabs");
const Skip = () => {
    tab.set("details")
}
const Github = () => {
    tab.set("details")
}
</script>

<div
	class="bg-dark-bgMuted2 w-[80%] h-[40%] rounded-2xl shadow-lg mt-6 p-6 font-montserrat flex justify-between flex-col">
	<div>
		<h1
			class="font-semibold text-black dark:text-white font-montserrat text-2xl">
			Import an existing repository
		</h1>
		<h6 class="font-normal text-black dark:text-white mt-1">
			Don’t have a repository? We’ll create one for you, so you can <span
				class="text-dark-color-accent cursor-pointer font-bold"
				on:click="{() => {
					tab.set('details');
				}}">skip this step.</span>
		</h6>
	</div>
	<div class="flex items-center justify-between">
		<div class="flex gap-4">
            <Buttons provider="Github" hasImage={true} onClick={Github} />
            <Buttons provider="Gitlab" hasImage={true} />
            <Buttons provider="Bitbucket" hasImage={true} />
        </div>
        <Buttons provider="Skip" hasImage={false} onClick={Skip} />
	</div>
</div>

// web/components/Projects/Pages/Provider.tsx
import React from "react";
import axios from "axios";
import { serverUrl } from "../../../utils/constants";

const GetGHToken = (name: string) => {
  axios.get(`${serverUrl}/api/auth/import/${name}`).then((resp) => {
    window.location = resp.data as any;
  });
};

const Provider = ({ setTab }) => (
  <div className="w-full h-auto flex items-center justify-center p-24 font-montserrat">
    <div className="bg-[#282E3B] w-full h-full drop-shadow-md rounded-md">
      <div className="p-6">
        <h2 className="font-bold lg:text-3xl md:text-xl">
          Import an existing repository.
        </h2>
        <h5 className="font-semibold mt-2">
          Don’t have a repository? We’ll create one for you, so you can{" "}
          <span
            className="text-dark-color-accent cursor-pointer"
            onClick={() => setTab("details")}
          >
            skip this step.
          </span>
        </h5>
        <div className="flex items-center pt-10 justify-between gap-2">
          {/* Style all of these components */}
          <div className="gap-2 flex">
            <button
              onClick={() => {
                GetGHToken("github");
              }}
            >
              Github
            </button>
            <button>GitLab</button>
            <button>BitBucket</button>
          </div>
          <div>
            <button>Skip</button>
          </div>
        </div>
      </div>
    </div>
  </div>
);
export default Provider;
