// web/components/Modals/Modal.tsx
import React, { Fragment } from "react";
import { Dialog, Transition } from "@headlessui/react";

interface ModalProps {
  children: React.ReactNode;
  isOpen: boolean;
  setIsOpen: any;
}

export const Modal: React.FC<ModalProps> = ({
  children,
  isOpen,
  setIsOpen,
}) => (
  <Transition.Root show={isOpen} as={Fragment}>
    <Dialog
      as="div"
      auto-reopen="true"
      className="fixed z-10 inset-0 overflow-y-auto"
      onClose={setIsOpen}
    >
      <div className="flex items-end justify-center min-h-screen pt-20 px-4 pb-20 text-center sm:block sm:p-0">
        <Transition.Child
          as={Fragment}
          enter="ease-out duration-300"
          enterFrom="opacity-0"
          enterTo="opacity-100"
          leave="ease-in duration-200"
          leaveFrom="opacity-100"
          leaveTo="opacity-0"
        >
          <Dialog.Overlay className="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" />
        </Transition.Child>

        <span
          className="hidden sm:inline-block sm:align-middle sm:h-screen"
          aria-hidden="true"
        >
          &#8203;
        </span>
        <Transition.Child
          as={Fragment}
          enter="ease-out duration-300"
          enterFrom="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
          enterTo="opacity-100 translate-y-0 sm:scale-100"
          leave="ease-in duration-200"
          leaveFrom="opacity-100 translate-y-0 sm:scale-100"
          leaveTo="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
        >
          <div className="bg-white inline-block align-bottom rounded-2-5xl px-4 pt-5 pb-4 overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-xl sm:w-full sm:px-3 sm:pt-4 sm:pb-10">
            {children}
          </div>
        </Transition.Child>
      </div>
    </Dialog>
  </Transition.Root>
);

export default Modal;

// web/src/lib/components/Modal.svelte
<script lang="ts">
export let isOpen: boolean;
console.log(isOpen);
</script>

<div
	class="{`z-10 inset-0 overflow-y-auto ${isOpen ? 'fixed' : 'hidden'}`}"
	aria-labelledby="modal-title"
	role="dialog"
	aria-modal="true">
	<div
		class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
		<div
			class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"
			aria-hidden="true">
		</div>
		<span
			class="sm:inline-block sm:align-middle sm:h-screen"
			aria-hidden="true">&#8203;</span>
		<div
			class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full">
			<div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
				<slot />
			</div>
		</div>
	</div>
</div>
